# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1402bc5eac38d73a3a24eff6d6837db27e723a2aad954159370f909ac14468a881f047886506ce92993dd924ba6d4b6d692f001d9d402cab2680074225cf06

test:
  secret_key_base: 73c8a880802f255fbed895787da65fa3df83c84b249e646ee3fd63852f988f77e57315d08fcd5dabcbf24831a69c8f7cc92fddbbf5b7af0c37d7a58373ed03f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
